# Automated Test Suite generated by Agentic SDLC QA Agent
import pytest
from app.utils import calculate

def test_calculate_valid_operands():
    assert calculate(10, 5) == 15
    assert calculate(3.14, 2.0) == 5.14

def test_calculate_invalid_type_raises_value_error():
    with pytest.raises(ValueError, match="Inputs must be numeric"):
        calculate("invalid_arg", 5)

def test_calculate_second_operand_invalid():
    with pytest.raises(ValueError, match="Inputs must be numeric"):
        calculate(5, [1, 2])
